hw4 model part first draft
could not link to 2d array lib functions. Similar problem as the one
posted on discussion board. Need to discuss with you

/tmp/ccslfYiU.o: In function `gameDef::set_extensionColor(int, int,
int*)':
/home/jackgu/Desktop/testdir/hw4/hw4_model.h:32: undefined reference to
`A2d_AllocateArray2d'
/home/jackgu/Desktop/testdir/hw4/hw4_model.h:36: undefined reference to
`A2d_FillArray2d'
/tmp/ccslfYiU.o: In function `gameDef::set_boardState(int, int, int*)':
/home/jackgu/Desktop/testdir/hw4/hw4_model.h:42: undefined reference to
`A2d_AllocateArray2d'
/home/jackgu/Desktop/testdir/hw4/hw4_model.h:46: undefined reference to
`A2d_FillArray2d'
/tmp/ccslfYiU.o: In function `gameDef::get_extensionColor_element(int,
int)':
/home/jackgu/Desktop/testdir/hw4/hw4_model.h:52: undefined reference to
`A2d_GetElement'
/tmp/ccslfYiU.o: In function `gameDef::get_boardState_element(int,
int)':
/home/jackgu/Desktop/testdir/hw4/hw4_model.h:55: undefined reference to
`A2d_GetElement'
collect2: error: ld returned 1 exit status